### ISSUE TITLE
Is tools support windows ?

### ISSUE THREAD

**Issue by InfiniteOpen** [magisterquis/curlrevshell#1]
Hi, My OS is windows 11 , when run the command "go install github.com/magisterquis/curlrevshell@latest"

I got error like that:
```
> go install github.com/magisterquis/curlrevshell@latest
go: downloading github.com/magisterquis/curlrevshell v0.0.1-beta.4
go: github.com/magisterquis/curlrevshell@v0.0.1-beta.4 requires go >= 1.22.1; switching to go1.22.2
go: downloading go1.22.2 (windows/amd64)
go: downloading golang.org/x/sync v0.7.0
go: downloading golang.org/x/term v0.19.0
go: downloading golang.org/x/net v0.24.0
go: downloading golang.org/x/tools v0.20.0
go: downloading golang.org/x/sys v0.19.0
go: downloading golang.org/x/text v0.14.0
# github.com/magisterquis/curlrevshell/lib/opshell
C:\Dev\Golang\1.21.4\pkg\mod\github.com\magisterquis\curlrevshell@v0.0.1-beta.4\lib\opshell\opshell.go:205:33: undefined: syscall.SIGWINCH
```

then i try to upgrade my go to 1.22.2 ,but nothing change.

so it's that possible run the program on windows ?

**Comment by magisterquis** [comment]
No, no Windows support's planned.  It may run on WSL though.

You can try getting rid of the parts which watch for window size changes, though that'll also break watching for window resizing.

Commenting out these may help:
https://github.com/magisterquis/curlrevshell/blob/v0.0.1-beta.4/lib/opshell/opshell.go#L125
https://github.com/magisterquis/curlrevshell/blob/v0.0.1-beta.4/lib/opshell/opshell.go#L202-L219

No guarantees, though; I don't have a Windows box to test it on.

**Comment by InfiniteOpen** [comment]
Thanks your answer, i will try other os.
